### ISSUE TITLE
Add Adobe XD support

### ISSUE THREAD

**Issue by 14rego** [kactus-io/kactus#101]
Sketch is a great place to start, but as you add more design platforms, here's my +1 for Adobe XD. Thanks for what you've done. Can't wait to join the fun. -- R

**Comment by mathieudutour** [comment]
I don't think Adobe XD have an open file format so I can't do anything. Also their "extension" platform is closed so I can't look at the docs.

So I'll close this because there is nothing I can do

**Comment by GarthDB** [comment]
@mathieudutour since the last comment, Adobe Xd has opened the platform documentation https://adobexdplatform.com/

**Comment by GarthDB** [comment]
I on not personally on the Xd team at Adobe, but I can get you in contact with them if you'd like.

**Comment by GarthDB** [comment]
@mathieudutour that would be awesome. I don't think I have any ability to solve the underlying issue of the open format, but I will apply pressure where I can.
