### ISSUE TITLE
Kactus failed to launch Invariant Violation: Minified React error #200

### ISSUE THREAD

**Issue by frederickk** [kactus-io/kactus#104]
## Description
After removing a local repo, I am unable to open Kactus. The app gets stuck in a loop of closing and reopening with the following error
```
Invariant Violation: Minified React error #200; visit https://reactjs.org/docs/error-decoder.html?invariant=200 for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
    at e.exports (/webpack:/renderer.js:10:1)
    at o (/webpack:/renderer.js:66:1)
    at Ir (/webpack:/renderer.js:66:1)
    at Object.render (/webpack:/renderer.js:66:1)
    at Object.<anonymous> (/webpack:/renderer.js:73:1)
    at t (/webpack:/renderer.js:1:1)
    at /webpack:/renderer.js:1:1
    at /webpack:/renderer.js:1:1
```

## Version
* Kactus:
0.3.7

* Operating system:
macOS High Sierra 10.13.4
MacBook Pro (13-inch, 2017, Four Thunderbolt 3 Ports)

## Steps to Reproduce
1. Remove local repo
2. Close Kactus
3. Re-open Kactus
4. Error appears, loop to 2

### Expected Behavior
Kactus opens as normal.

### Actual Behavior
The app gets stuck in a loop of closing and re-opening. The only way to end it is to restart my computer.

## Additional Information
![screen shot 2018-06-10 at 22 44 04](https://user-images.githubusercontent.com/513134/41214354-cedf5924-6cff-11e8-840c-06881bfe3318.png)

I removed Kactus and all of the associated directories and preference files. Re-downlaoded and installed, yet the error persists.

### Logs
[2018-06-11.kactus.production.log](https://github.com/kactus-io/kactus/files/2088822/2018-06-11.kactus.production.log)

**Comment by patrickplaggenborg** [comment]
I get the same error message when trying to open Kactus (for the first time).

**Comment by davidmead-dt** [comment]
Had an update to Kactus.  Upon restart I get this error.  Quit & restart doesn't clear it. Force quit doesn't work.

**Comment by eyeruham** [comment]
I'm also experiencing this issue, right after updating to the newest version

**Comment by aussieboi** [comment]
👍

**Comment by derozic** [comment]
Same issue, brand new install

**Comment by mathieudutour** [comment]
Really sorry about that, I just started the publication of 0.3.8 which fixes that (should appear in a few minutes). Sorry again

**Comment by frederickk** [comment]
I downloaded the latest 0.3.8 and all was going well... until I made a new branch and attempted toggling between the new branch and master.

I'm not seeing the following error (and stuck in the quit-restart loop):

![screen shot 2018-06-11 at 17 38 27](https://user-images.githubusercontent.com/513134/41263892-96915168-6d9e-11e8-89b6-dcab488f2aed.png)
