### ISSUE TITLE
History tab's right side is stuck in "loading" mode

### ISSUE THREAD

**Issue by ilteris** [kactus-io/kactus#106]
Hello,

First and foremost, great application, thank you for providing this for us for free. I have set it up no problem, but I have noticed I cannot see anything on the right hand side (always rotating arrows) when I pick commits in History tab on the left. Is this expected? Is there a workaround? The changes in the commit are just 5 files, so it's not a big change and it showed up before I committed this in Changes tab. 

Any direction is appreciated.

**Comment by mathieudutour** [comment]
Ah indeed. It should be fixed in v0.3.11 (deploying now, should be live in a few minutes)
