### ISSUE TITLE
Error attempting to build Kactus from source ("Failed to load resource: net::ERR_CONNECTION_REFUSED" error when running build)

### ISSUE THREAD

**Issue by ben21-21** [kactus-io/kactus#107]
## Description
Build Kactus from source. Appears to build correctly, launch application, no windows appear automatically, if manually trigger any windows via the macOS menu then get "Failed to load resource: net::ERR_CONNECTION_REFUSED" in reference to renderer.js file.

## Version
* Kactus: Tested with 0.3.10 source and head (0f86911)
* Operating system: macOS High Sierra 10.13.4

## Steps to Reproduce
- Pull latest Kactus source
- npm install dependencies
- tsc build typescript
- npm build: dev
- Run successfully built application from dist folder
- No windows appear
- If manually trigger window, for instance via "About Kactus" get a blank window, with error noted above outputted in console

**Comment by mathieudutour** [comment]
you need to run `npm run start`. It will launch a window automatically with hot-reload
