### ISSUE TITLE
Auto update reverts app back to v0.3.10

### ISSUE THREAD

**Issue by ilteris** [kactus-io/kactus#109]
The latest version of the app on Github release is 0.3.12. I download and use it just fine. However, auto update forces me to install 0.3.10 and there's no way around it. (No disable auto update). So it always reverts back to 0.3.10. 

Thought you would like to know.

Thanks!

**Comment by mathieudutour** [comment]
hum that's odd, the update server might not have been updated maybe? let me check

**Comment by mathieudutour** [comment]
indeed that was it. Fixed now
