### ISSUE TITLE
Subscription Active, but Can't Publish

### ISSUE THREAD

**Issue by NerdCowboy** [kactus-io/kactus#110]
## Description

I unlocked an Enterprise account, but when I try to publish the branch to remote, I get a "Unlock the full potential of Kactus" modal and am unable to proceed. I tried quitting and restarting and that doesn't seem to change anything.

## Version

* Kactus:
0.3.12

* Operating system:
10.13.3

## Steps to Reproduce

1. We received a code to evaluate Enterprise free for a month. I went into the settings and entered the code and was able to ensure that the subscription was unlocked in the settings panel. 
2. I made a minor change to a Sketch file.
3. Commit change
4. Hit publish branch
5. An unlock modal is displayed. 

### Expected Behavior

To be able to push my branch to remote

### Actual Behavior

An unlock modal is displayed
 

### Logs

[2018-07-17.kactus.production.log](https://github.com/kactus-io/kactus/files/2203416/2018-07-17.kactus.production.log)

**Comment by brentCVS** [comment]
Ya, that was mostly because you require users to sign up with Github, but we're using Gitlab, so I just used my personal account to sign in to Kactus. Regardless, I tried signing up with Github with my work email and then signed into Kactus with that account and I still have the same issue.

**Comment by mathieudutour** [comment]
No I mean your gitlab credentials might be wrong: the logs show this:
```
[AppStore.getAccountForRemoteURL] found generic credentials for 'gitw.cvshealth.com/PBM' and 'BrentP.Larson'
[ui] Executing clone: git -c credential.helper= clone --recursive --progress -- https://gitw.cvshealth.com/PBM/XP_Labs/sketch-files.git /Users/c059129/Sites/sketch-files (took 1.044s)
[ui] `git -c credential.helper= clone --recursive --progress -- https://gitw.cvshealth.com/PBM/XP_Labs/sketch-files.git /Users/c059129/Sites/sketch-files` exited with an unexpected code: 128.
Cloning into '/Users/c059129/Sites/sketch-files'...
remote: HTTP Basic: Access denied
fatal: Authentication failed for 'https://gitw.cvshealth.com/PBM/XP_Labs/sketch-files.git/'
```

so the credentials you gave kactus to access your gitlab repo might have a typo

**Comment by mathieudutour** [comment]
wait now I'm confused. Did you try restarting Kactus and trying to push again? Maybe the account store wasn't properly updated?

Could you give me your logs again as well, I don't see any logs regarding a push?

**Comment by NerdCowboy** [comment]
Attempting to push just pops up the upgrade modal even though in my preferences, it shows my account as being unlocked, so I think that's why you're not seeing anything in the logs about pushing.

See attachments for logs. You're also going to see some errors about Git LFS in there. We were testing out a similar app, Folio, and I think they caused that error, but there's a chance it could have been introduced by Kactus.

[2018-07-17.kactus.production.log](https://github.com/kactus-io/kactus/files/2207506/2018-07-17.kactus.production.log)
[2018-07-18.kactus.production.log](https://github.com/kactus-io/kactus/files/2207507/2018-07-18.kactus.production.log)

**Comment by mathieudutour** [comment]
Oh it's because you choose the premium plan instead of the enterprise plan. To use a repo on gitlab, you need an enterprise license. I changed it for you. It should be ok now.

**Comment by NerdCowboy** [comment]
It's still happening. I signed out of Kactus and quit, deleted the repo, restarted Kactus, re-signed in to Kactus, and the upgrade modal is still showing despite it showing it's unlocked in my preferences.

**Comment by mathieudutour** [comment]
you are logging in with `NerdCowboy` right?

**Comment by NerdCowboy** [comment]
No, I was logging in with my other account. Just logged in with this one and it worked. Thanks!

**Comment by NerdCowboy** [comment]
Can you also add @gjlaubenstein so we can test merging?

**Comment by mathieudutour** [comment]
done
