### ISSUE TITLE
Enterprise licensing without a premium GH account

### ISSUE THREAD

**Issue by rvr** [kactus-io/kactus#112]
I'm trying to buy multiple licenses for my team, but do not have a premium GH license. We are going to use Kactus with GH Enterprise, so we need to unlock the app, but we are not working on public GH.

I'd like to be able to purchase multiple licenses without having to authorize against a premium account on public GH. I work in an org that has GHE, but does not have a public GH account at this time.

At this point it seems we'd have to buy each license individually.

Ideally, I could simply pay for a number of licenses, and receive unlock codes, or manage email addresses that can receive invites. This example from [Nucleo](https://nucleoapp.com) show a simple team management interface.

<img width="780" alt="screen shot 2018-08-23 at 12 29 07 pm" src="https://user-images.githubusercontent.com/28814/44538762-51c3e080-a6d0-11e8-98fc-5857d1132b22.png">

**Comment by mathieudutour** [comment]
You do not need a premium GH account, just a regular one. I'm using GH as a way to identify people, to not have to use an email/password system.

Your colleagues can sign up with both their enterprise account and regular one in Kactus.
