### ISSUE TITLE
Confused with how to manage the actual .sketch files

### ISSUE THREAD

**Issue by steveharman** [kactus-io/kactus#116]
I'm up & running with Kactus using BitButcket.  I'm able to add commits, push & pull changes to the  Kactus folder that contains all the .json etc.  My question is how to manage the actual .sketch file itself.

When setting up Kactus I accepted the recommended setting of ignoring .sketch files.  So assuming I am collaborating on work with another remote designer - how do we go about sharing the actual .sketch file as it's not in the repo?    Setting up Bitbucket and Kactus itself was pretty straightforward, but I'm unclear on the relationship between my regular .sketch file and the ".json folder' created by Kactus.  

- How does the Sketch file update the .json folder after I've made changes in Sketch (is this what the Kactus app does?)
- If I've accepted the recommended setting in Kactus of not tracking .sketch files, how does my remotely located colleague access the .sketch file after they've cloned the repo?  
- Should I email my colleague the .sketch and ask them to add it to their local repo, or is it just easier to ignore the recommended setting in Kactus and have the .sketch file pushed to BitBucket?

One final question - what are the subscription packages about please?  Is there a difference between the binary on Github and the one available via Kactus.io ?

Many thanks,

**Comment by mathieudutour** [comment]
The whole purpose of Kactus is to turn the json folder into a sketch file and vice versa. So you do not need to share the sketch file directly: when your colleague will pull your changes via Kactus, it will automatically build up the sketch file from the json folder.

I'm not sure what you by your last question

**Comment by steveharman** [comment]
Brilliant, that makes perfect sense now, thanks.   

The second part of the question related to https://kactus.io/pricing/ 

There's a build of Kactus available for download here on Github which hasn't asked me for a licence key or payment and seems to work with private repo's and BitBucket.  But the pricing page at https://kactus.io/pricing/ seems to indicate that to get a version of Kactus which works with private repos and BitBucket would be $11.99 a month?

Thanks again.

**Comment by mathieudutour** [comment]
The builds are the same. I'm guessing you haven't logged in with GitHub and when there is no user logged in, I'm trying to be nice and not block people. But if you like Kactus, consider buying a license :)

**Comment by steveharman** [comment]
Sure thing, understood.  If it turns out to be as useful as I think it will be, we certainly will.

Thanks
