### ISSUE TITLE
Kactus-io access

### ISSUE THREAD

**Issue by viestat** [kactus-io/kactus#119]
### Description

When authorizing kactus-io to access I discovered that it requires `full access` to **Personal user data**
I do not see of any reason why this application would need **write** access on the users personal data. 

Maybe you can help clarify this and/or remove this scope

<img width="508" alt="screenshot 2018-10-15 at 4 27 47 pm" src="https://user-images.githubusercontent.com/9158996/46957793-9a789400-d098-11e8-8c8d-05e1474a80bc.png">

**Comment by mathieudutour** [comment]
Indeed, Kactus doesn't need write access for now. I think I was just planning ahead as it's not easy to modify scopes once granted.

No need to worry tho, all the calls are here: https://github.com/kactus-io/kactus/blob/master/app/src/lib/api.ts and the token is securely stored in the keychain.

I might change the scopes to `['repo', 'read:user', 'user:email']` which should be enough for now
