### ISSUE TITLE
Support for Google Web Designer

### ISSUE THREAD

**Issue by dardub** [kactus-io/kactus#122]
Hi. I just found out about your product and really interested in trying it out. I see that so far it only supports Sketch which makes a lot of sense.

Have you considered adding support for Google Web Designer? Source files in GWD are composed like a static website with some JSON configuration.

I've requested the designers at my company to use github desktop to version these files, but they still find it difficult.

I'm thinking that since the aim of Kactus is to make git version control more accessible to designers, this could be another good target application.

Thanks.

**Comment by mathieudutour** [comment]
I'm not familiar with GWD. Is there a way to generate previews for the files?

**Comment by dardub** [comment]
We use Google Web Designer for building HTML banner ads. I don't believe it generates any image previews. When you "Preview" in GWD it opens the browser to view the rendered HTML.
