### ISSUE TITLE
Can not preview without Kactus

### ISSUE THREAD

**Issue by abitrolly** [kactus-io/kactus#124]
> “I try to browse project artwork without Kactus installed. I found `kaktus.json` at the root, which points to `./assets` as root. Inside I found only one dir `icons/` full of nested `.json` files. I do not understand what art is inside. ”

**[Optional] Do you have any potential solutions in mind?**

For `icons/` dir in https://github.com/kactus-io/kactus/tree/master/assets/ generate `icons.png` at the same level with a low resolution to give an idea.

**Comment by mathieudutour** [comment]
No the whole point is not to put binary files (sketch files or images) in git so that you can merge things

**Comment by abitrolly** [comment]
But you merge with Kactus, which can ignore previews, no?

**Comment by mathieudutour** [comment]
git is the underlying tech. Kactus is just based on it
