### ISSUE TITLE
Delete Sketch file after renaming

### ISSUE THREAD

**Issue by riverbrandon** [kactus-io/kactus#125]
## Description
After renaming a Sketch file in my repo, along with the Kactus folder, and committing the changes, the old Sketch file does not get removed for others working in the repo.

## Version
* Kactus: 0.3.16
* Operating system: 10.12.6

## Steps to Reproduce
1. I have a file named `my-design.sketch`, and a corresponding folder called `my-design`
2. I rename both of them to `final-design.sketch` and `final-design`
3. I commit and push my changes
4. Someone else pulls the latest commits and then now have `final-design.sketch`, a folder named `final-design`, and a file named `my-design.sketch`
5. They are able to delete `my-design.sketch` without needing to commit any changes, indicating that it's now untracked

### Expected Behavior
When someone else pulls my changes, the file named `my-design.sketch` should be removed from their local repo.

### Actual Behavior
The renamed file remains with it's original name, while the new version is added.

**Comment by mathieudutour** [comment]
Nice find! I'll see how to fix it

**Comment by mathieudutour** [comment]
Should be fixed in 0.3.17
