### ISSUE TITLE
Library preview not working

### ISSUE THREAD

**Issue by rvr** [kactus-io/kactus#126]
## Description
With a Sketch library file, you can add a library preview artboard and it will show up as the image in the libraries list in Sketch preferences. With our library files in Kactus, these previews do not work. When I take the library files out of Sketch, open them and touch the preview artboard, it seems to work again.

## Version

* Kactus: 0.3.17

* Operating system: 10.12.6

## Steps to Reproduce
1. Create a Sketch file, add an artboard titled 'Library Preview' that is 100x80 (or a multiple), and add some element to it
2. Import that file as a library in Sketch preferences and you should see the preview you created
3. Do the same with a file that is in a Kactus repo, then import that as a library in Sketch preferences, and you will see the default library link icon
4. If I make a change to the preview, such as adding a shape, it will show up again in Sketch preferences, but doesn't seem to persist when switching branches or between commits

### Expected Behavior
I should see the library preview I created

### Actual Behavior
I get the library link icon, not the custom preview image

## Additional Information

<img width="584" alt="screen shot 2019-01-30 at 8 41 05 pm" src="https://user-images.githubusercontent.com/28814/52024881-6bafed80-24d0-11e9-8491-78a8be724d02.png">
<img width="765" alt="screen shot 2019-01-30 at 8 40 52 pm" src="https://user-images.githubusercontent.com/28814/52024886-6d79b100-24d0-11e9-8418-82627cfb9b08.png">
<img width="539" alt="screen shot 2019-01-30 at 8 40 39 pm" src="https://user-images.githubusercontent.com/28814/52024888-6fdc0b00-24d0-11e9-85b4-99db2307455e.png">

**Comment by mathieudutour** [comment]
Thanks for the nice bug report!

It should be fixed in 0.3.18 (which is currently deploying)
