### ISSUE TITLE
Kactus failed to launch 'TypeError: Cannot read property 'replace' of undefined'

### ISSUE THREAD

**Issue by MattAtG3** [kactus-io/kactus#128]
## Description
I cloned a repository that was created and uploaded to GH by another employee using Kactus. I selected the project. I immediately received the error "Kactus failed to launch".

TypeError: Cannot read property 'replace' of undefined
    at a.exec (/webpack:/renderer.js:6:1)
    at ChildProcess.exithandler (child_process.js:279:7)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)

I am now stuck in an unrecoverable loop where Kactus won't launch due to error, but I cannot quit or force quit because kactus starts up and jumps into the error.

Per instructions, I have restarted Kactus several times. Each time, I get this error. I uninstalled kactus, downloaded from the kactus.io from the website and reinstalled kactus. Both versions were 0.3.19 of kactus. I received the same error on startup.

I killed all Kactus processes use ps -eaf | grep kactus and kill -9 ... (because Kactus kept looping into the error). I deleted the /Users/username/Library/Saved Application State/io.kactus.KactusClient.savedState and restarted kactus. Same error.

I killed all Kactus processes. I deleted all my repos from /Users/username/Documents/Kactus. Restarted kactus. Kactus started telling me it couldn't find my repos.

## Version

* Kactus: 0.3.19

* Operating system: Mac OS 10.14.2

### Expected Behavior
Kactus to launch

### Actual Behavior
Kactus launched with error and there was no way for me to quit or recover.

### Logs

[2019-02-08.kactus.production.log](https://github.com/kactus-io/kactus/files/2846393/2019-02-08.kactus.production.log)

**Comment by MattAtG3** [comment]
The GH repo is private, but I am will to allow you access to debug Kactus.

**Comment by mathieudutour** [comment]
It'd be really helpful to have access to the repo yes

**Comment by MattAtG3** [comment]
@mathieudutour I gave you read access to https://github.com/GriffinGroupGlobal/DesignOps-Core which should allow you to clone the repo. That being said, I just tried to clone it and it worked this time.  I'm not sure what happened the other time, but I figure I'll let you try and clone it and see if anything breaks. If not, we can close the issue.

FYI, My design team really likes using Kactus with GH, so thanks.

**Comment by mathieudutour** [comment]
Glad to hear that!

First thing: you shouldn't keep the `.sketch` file in git. https://kactus.io/help/how-to/#existing-repos

Second thing (and I think that's why it broke): the sketch file must have pages with the same names which makes it hazardous to transform into JSON.

If you have a clean sketch file, I'd recommend making sure the pages have different names, then start again with a clean repo

**Comment by MattAtG3** [comment]
Thanks!
