### ISSUE TITLE
Kactus build command not working with AWS

### ISSUE THREAD

**Issue by bjp232004** [kactus-io/kactus#131]
Hi Team,

This is a wonderful contribution.

I have tried to do the same setup in my local system which is working fine. But when I am trying to do the setup in AWS FREE TIER account via EC2 instance, BUILD:prod command is not working. It hangs/stuck while building.

NodeJS Version: 10.15.3
Installed Python and GIT

Can you please suggest if anything wrong and you already have an instance working in AWS?

Thanks

**Comment by mathieudutour** [comment]
Why not building it on your local machine? EC2 might have some restriction about directories that node use, I'm not sure
