### ISSUE TITLE
restore an early version

### ISSUE THREAD

**Issue by Gapachec** [kactus-io/kactus#132]
Hello!  This might be a stupid question but im a designer first time using git / kactus .. anyway so far i can do everything right except one thing 

I have a file and for example deleted all .. i want to restore toa file from 2 days ago .. and for the life of me cant figure out how to do it.. 

I can see the history tab and can see the changes but how can i restore it?

If you can help woud be awesome.. thanks

**Comment by mathieudutour** [comment]
In the History tab, when you click on a commit, you should see an "Open Sketch file" button. Click on it and then replace your file by the newly opened one.

Hope that helps!
