### ISSUE TITLE
can not push to main

### ISSUE THREAD

**Issue by Gapachec** [kactus-io/kactus#133]
Hello, i tried kactus and so far works well .. i have figured it out my merges branches and all .. since im not programer.. 

However i shared my project with people and they are able to download and update and everything.. but they do changes and when the push to origin they get an error wich is this.

<img width="1080" alt="Screen Shot 2019-06-13 at 3 58 09 PM" src="https://user-images.githubusercontent.com/47638674/59467074-6d7dac00-8df4-11e9-8e70-26378bccd1ef.png">

I read the link that is there about git protection branches but 1) the page dont have the same options as i have (corporate) . and 2.. i Asked to my programmer friends and said i should ivite and give pushing capabilities to the person so they can do it with a review..   wich i did 

<img width="591" alt="Screen Shot 2019-06-13 at 4 03 10 PM" src="https://user-images.githubusercontent.com/47638674/59467232-c3525400-8df4-11e9-8144-340cede2b3e2.png">

but still they get the same error 

<img width="1743" alt="Captura de pantalla 2019-06-13 a la(s) 15 29 01" src="https://user-images.githubusercontent.com/47638674/59467264-db29d800-8df4-11e9-9dbf-60e383357b2a.png">

and we dont know what to do :/

**Comment by mathieudutour** [comment]
I'm guessing your master is protected and cannot be pushed directly to.
So they either need to create a new branch and push it or you need to remove the protection (on your github repo -> Settings > Branches > remove the protection rule)
