### ISSUE TITLE
Dev tools open at launch

### ISSUE THREAD

**Issue by yceballost** [kactus-io/kactus#137]
## Description
When I launch Kactus app, dev tool appear opened.

## Version
* Kactus: 0.3.22
* Operating system: Mac OS High Sierra 10.13.6

## Steps to Reproduce
Just when I open the app, all times.

### Expected Behavior
No open dev tool at launch

### Actual Behavior
When I launch Kactus app, dev tool appear opened.

## Additional Information
![Screen Shot 2019-09-26 at 22 39 48](https://user-images.githubusercontent.com/6722153/65723384-94fc3a00-e0ae-11e9-9aaa-7ee43ea70f92.png)

**Comment by davo** [comment]
I can confirm this behavior as well on macOS Catalina 10.15 Beta (19A573a).

**Comment by mathieudutour** [comment]
should be fixed on 0.3.25
