### ISSUE TITLE
Installed latest update 27. September 2019, 

### ISSUE THREAD

**Issue by hbxes** [kactus-io/kactus#138]
## Version

* Kactus:

* Operating system:
MAC OS 10.14.6

### Expected Behavior

I expected that kactus normally opens

### Actual Behavior

I just get a blanc screen...
<img width="1348" alt="Bildschirmfoto 2019-09-27 um 13 00 50" src="https://user-images.githubusercontent.com/55880422/65766744-29f14880-e12c-11e9-9fd2-8324a4b590ea.png">

**Comment by mathieudutour** [comment]
I'm on it 👍

**Comment by mathieudutour** [comment]
should be fixed
