### ISSUE TITLE
Visual file diffs not rendering correctly

### ISSUE THREAD

**Issue by bsmart** [kactus-io/kactus#14]
### Description

Image diffs not rendering accurately.

### Version

**Kactus version:** 0.1.6

**OS version:** 10.12.5

### Steps to Reproduce

1. Create a sketch file from the Kactus app
2 . Save file in Sketch app
3. Alter Sketch file and save again
4. Click on changed file in Kactus
5. Only one file is shown w/wrong colors and the 2-up, swipe, onion skin, and difference are not selectable

**Expected behavior:** I expected to see the old file and new file correctly rendered in Kactus.

**Actual behavior:** I saw the most recent file only and the colors are not correct.

**Reproduces how often:** 100%

#### Additional Information

Original in Sketch:

https://www.dropbox.com/s/lxuc1b4wft2mzwa/Screenshot%202017-07-17%2012.07.42.png?dl=0

Kactus Diff

https://www.dropbox.com/s/cmj10a0h0zc2vje/Screenshot%202017-07-17%2012.07.30.png?dl=0

**Comment by mathieudutour** [comment]
Hum weird, could you zip your project and put it here?

**Comment by bsmart** [comment]
Yeah, it looks like my files inside of mockup are disorganized...

[barcode-app.zip](https://github.com/kactus-io/kactus/files/1153910/barcode-app.zip)

**Comment by mathieudutour** [comment]
hum I'm having a hard time trying to reproduce the color mismatch :/

Yes exactly. One thing tho: you want to add `*.sketch` to your `.gitignore`

**Comment by bsmart** [comment]
Thanks for the `.gitignore` tip!

I removed and reinstalled Kactus and opened my https://github.com/bsmart/portfolio repo and everything seems to be working as expected now.

**Comment by mathieudutour** [comment]
Hum that's a bit annoying not to be able to find why it was like that. But well ¯\_(ツ)_/¯

Thanks for the bug report anyway
