### ISSUE TITLE
Weirds artboards appears

### ISSUE THREAD

**Issue by yceballost** [kactus-io/kactus#148]
### Describe the bug

After commits some pull request, I found a lot of blank artboards with a name similar to `E719C5E6-9DFB-4E21-8EC9-239939AC5C7B`

### Version & OS

0.3.29
(but I saw this issue in versions before)

### Steps to reproduce the behavior

I don't know how to reproduce, I know that it is common when I merge pull requests.

### Screenshots

![Screenshot 2020-04-03 at 13 55 57](https://user-images.githubusercontent.com/6722153/78358312-470f4400-75b3-11ea-8121-8188df395fbd.png)

(sorry Mathieu for creating a lot of issues 🙏)

**Comment by mathieudutour** [comment]
I'd be super useful if next time it happens, you could invite me to the repo so that I can have a look

**Comment by yceballost** [comment]
I never saw this bug again. You can close it. I think that was caused because I was working with big file sizes.

**Comment by mathieudutour** [comment]
Ah cool. I haven't seen it either
