### ISSUE TITLE
Can't reach image-diff TabBar

### ISSUE THREAD

**Issue by mitsuyoshi-yamazaki** [kactus-io/kactus#15]
In some situations I can't reach TabBar on image-diff view.

### Description

When Kactus window height is too small compare to an artboard height, TabBar (2-up, Swipe, Onion Skin, Difference) is located on outside of the window so I can't reach it.

![_2017-07-18_10_34_48](https://user-images.githubusercontent.com/904354/28297084-e6c239b8-6ba6-11e7-8ea7-dd70dd69e116.png)

### Version

**Kactus version:** 0.1.6

**OS version:** 10.12.5

### Steps to Reproduce

1. Create diffs on an artboard.
2. Show the diffs on Kactus
3. Resize Kactus window smaller height than the artboard height

**Expected behavior:** [What you expected to happen]

I can always reach TabBar

**Actual behavior:** [What actually happened]

In the situation I described above I can't.

**Reproduces how often:** [What percentage of the time does it reproduce?]

100%

### Logs

None.

#### Additional Information

Making image-diff area scrollable could fix.

**Comment by mathieudutour** [comment]
Yeah just fixed it a few moments ago, testing a bit more and releasing it tomorrow morning

**Comment by mathieudutour** [comment]
fixed in 0.1.7
