### ISSUE TITLE
Update v0.3.30 crash app

### ISSUE THREAD

**Issue by yceballost** [kactus-io/kactus#152]
### Describe the bug

After update app, the main window doesn't appear.

### Version & OS

Kactus v0.3.30
System macos 10.15.6

### Screenshots

![Screenshot 2020-10-28 at 15 57 22](https://user-images.githubusercontent.com/6722153/97453887-75c97f00-1936-11eb-8bb5-dcd1fc71283d.png)

### Logs

[2020-10-28.kactus.production.log](https://github.com/kactus-io/kactus/files/5452757/2020-10-28.kactus.production.log)

**Comment by anthonymiao** [comment]
same here, it's blocking my work now

**Comment by yceballost** [comment]
solved in my case with the new version

https://github.com/kactus-io/kactus/releases/tag/v0.3.31
