### ISSUE TITLE
Kactus import when focus window

### ISSUE THREAD

**Issue by yceballost** [kactus-io/kactus#153]
### Describe the bug

When you change a branch, Kactus doesn't show feedback about the files are regenerated, but when you go to another app and come back to Kactus, the "refresh arrow" spins.

### Version & OS

Mac OS 10.15.6
Kactus 0.3.32

### Steps to reproduce the behavior

1. Change to other branch
2. Change window focus to other app
3. Change to Kactus app
4. See the spining arrows

### Expected behavior

I think the expected behavior will be the arrows and the process to regenerate the files have to do at the moment that you change to other branch.

### Actual behavior

Spining arrows spining after lost the window focus and recover again

### Screenshots
https://user-images.githubusercontent.com/6722153/108538948-a9faee00-72df-11eb-974f-32d3e8878cbb.mov

**Comment by mathieudutour** [comment]
Ah thanks for the report. Kactus is actually parsing the files when checking out a branch but I forgot to show the loading indicators. Should be fixed in 0.3.33
