### ISSUE TITLE
No changes in change list

### ISSUE THREAD

**Issue by yceballost** [kactus-io/kactus#154]
### Describe the bug

The main feature is not working, when I edit a sketch file, then I go to Kactus and no changes appears.

### Version & OS

0.3.33
Mac OS 10.15.6

### Steps to reproduce the behavior

1. Go to sketch file
2. make a change and save
3. go to kactus
4. See no changes in change list

### Expected behavior

as always, changes appears in change list

### Logs

Logs dont show anything when I save and go to Kactus.

### Additional context

Maybe kactus is not checking for this changes when you have Kactus on focus

**Comment by iantodd87** [comment]
Having the same issue.

**Comment by yceballost** [comment]
solved with `0.3.34`
