### ISSUE TITLE
Kactus.io organization page

### ISSUE THREAD

**Issue by yceballost** [kactus-io/kactus#158]
### Describe the bug

Dont load user information
<img width="1204" alt="image" src="https://user-images.githubusercontent.com/6722153/161028744-f86666f8-3e8e-42c4-a6bc-20c0198a7143.png">

### Steps to reproduce the behavior

1. Go to 'kactus.io/org'

**Comment by mathieudutour** [comment]
hum, anything in the console?

**Comment by yceballost** [comment]
Maybe was a cache thing! I did logout and login and now is working fine!

**Comment by mathieudutour** [comment]
Ah cool! Let me know if it comes back
