### ISSUE TITLE
Windows build

### ISSUE THREAD

**Issue by nblackburn** [kactus-io/kactus#16]
A Windows build would be good to have because not all designers use a Mac.

**Comment by mathieudutour** [comment]
very true but this only works with Sketch which is only available on Mac

**Comment by simonds** [comment]
Windows has Lunacy for working with Sketch files (https://icons8.com/lunacy). How about a Windows port now? :)

**Comment by mathieudutour** [comment]
They don’t expose any renderer so it’s not possible to preview the changes

**Comment by simonds** [comment]
How about using something like this: https://github.com/AnimaApp/sketch-web-viewer
