### ISSUE TITLE
Lost the ability to see/compare side-by-side what's been deleted/added

### ISSUE THREAD

**Issue by happyfunmeowmeow** [kactus-io/kactus#21]
### Description
When I update my sketch file and go to Kactus to reflect the change, I no longer see the side-by-side view of what was deleted/added.

### Version
- Kactus version: 0.1.9
- OS version: macOS Sierra version: 10.12.3

![intended_view](https://user-images.githubusercontent.com/12299917/28382768-441fb87e-6c8d-11e7-92c4-b7f4af1739e6.png)

![current_view](https://user-images.githubusercontent.com/12299917/28382773-473401a0-6c8d-11e7-8526-0c08366fc7e9.png)

**Comment by mathieudutour** [comment]
So I'm not sure what is happening. Am I correct that you are doing:
- create a new sketch file
- add a picture
- commit
- change the picture

and then the picture is shown as added instead of replaced?

**Comment by sushislice** [comment]
I have the sketch file created.
- add photo
- edit photo
- commit
- <repeat>

The new version displays only what was added. it doesn't show it side-by-side the previous version and the updated version.

**Comment by mathieudutour** [comment]
wait, if you don't commit in between, it won't show the diff. The diff is between the current version and the previous commit

**Comment by sushislice** [comment]
Sorry, there was supposed to be a bullet in between 'add photo' and 'edit photo'; But yes, I am committing in between. Yet I still don't see the side-by-side current vs previous commit.

**Comment by mathieudutour** [comment]
Hum. How exactly do you edit the picture?

**Comment by sushislice** [comment]
The same way in the demo you provided here: http://kactus.io/help/how-to/

**Comment by sushislice** [comment]
Sorry, I'm terrible at words (ESL). Yes, I am adding layer onto the artboard. So I'm adding to the artboard and committing for each time I do.

**Comment by mathieudutour** [comment]
How do you "edit the photo"? Is it removing the old and adding a new one?

I'm not sure what you are doing but basically, when you add a new image (in place of another one), because their names are super different (it's an id), git thinks the old one is deleted and a new one is added (instead of thinking it's changed).

I don't think I can do anything there but you should still be able to see the artboard file (the one with the yellow dot on the right), right?

**Comment by happyfunmeowmeow** [comment]
Hey hey~ Someone came by to help me and I showed him. He played around with it and got it to work since I was able to show him in person, it was helpful for him to understand what I was trying to convey. So sorry for the trouble!!!

**Comment by mathieudutour** [comment]
Glad to hear that!

I'm closing this then
