### ISSUE TITLE
Repository Settings not working properly if updating kactus.json outside 

### ISSUE THREAD

**Issue by raulalgo** [kactus-io/kactus#22]
Trying to set text styles to share I've set it up initially through the interface to false. Afterwards I've updated kactus.json through an external editor. The change was caught up and commited by Kactus but no styles would be shared across the sketch files. Checking the repository settings through the UI again it would be still set to false, and no matter the change I would do on them, even deleting the kactus.json file, every time I open that panel the initial setting would be there. It only went away after deleting the file and restarting Kactus.

**Comment by mathieudutour** [comment]
So to be clear:
* changed the config through the interface
* the kactus.json was created
* changed the kactus.json externally
* change isn't reflected
?

**Comment by mathieudutour** [comment]
Oh found it. Will publish soon

**Comment by raulalgo** [comment]
Thank you very much!
