### ISSUE TITLE
Revert to commit that has been pushed to github

### ISSUE THREAD

**Issue by yoneth** [kactus-io/kactus#23]
I was wondering how to revert back into commit that has been pushed to github without having to touch CLI?

Is this possible at the moment?

Awesome app by the way!
Cheers

**Comment by mathieudutour** [comment]
Not yet, there is a bunch of edge cases that are hard to deal with.
What is your use-case exactly?

**Comment by mathieudutour** [comment]
I don’t think I want to support reverting to a pushed commit but in https://github.com/kactus-io/kactus/commit/7f5bb297fcfae775c69eb8ed36956896b294566b I add a button to open an old sketch file from the history. It is a temporary file and you shouldn’t use it for anything except seeing it and possibly copying from it
