### ISSUE TITLE
Seeing an error messsage with the repo.

### ISSUE THREAD

**Issue by aacrouch** [kactus-io/kactus#28]
### Description

[getting an error every time I go to the main screen of my repo.]
<img width="867" alt="screenshot 2017-07-21 09 47 31" src="https://user-images.githubusercontent.com/3729049/28468835-c687960c-6df9-11e7-9776-08e96b6b7d69.png">

### Version

**Kactus version:** [0.1.12]

**OS version:** [10.12.5]

### Steps to Reproduce

1. [Open repo]
2. [Go to the changes tab]

**Expected behavior:** [More detailed information about the error that I can understand and how to fix it.]

**Actual behavior:** [What actually happened]

**Reproduces how often:** [What percentage of the time does it reproduce? 100%]

**Comment by mathieudutour** [comment]
hum weird, could you zip your folder and send it to me?

**Comment by aacrouch** [comment]
Sent. Sorry for the delay.

**Comment by aacrouch** [comment]
@mathieudutour bumping this ...

**Comment by mathieudutour** [comment]
I’m not sure, it’s a git issue and I haven’t been able to reproduce
