### ISSUE TITLE
Unable to link to existing github repository

### ISSUE THREAD

**Issue by mwagz** [kactus-io/kactus#29]
Hey team!

First off, love this software and looking forward to using it!

### Description

Unable to link to existing repository. I have setup and pushed to a repository once with the application, but decided I wanted to move this to a more local directory to the software I work with. This is a private repository. When I select Repository > Repository Settings, I am presented with either Publish a new repo to my org on Github, or signing into an Enterprise server. What I would like to do is enter an existing repository URL and link these two up.

### Version

Showing on version [0.1.12](http://kactus.io/release-notes/).

**Kactus version:** 0.1.12

**OS version:** OSX 10.11.6 El Capitan

### Steps to Reproduce

1. Click Repository
2. Click Repository Settings...
3. Attempt to link to an existing private repository on Github.

**Expected behavior:** I expected to be able to link to an existing private repository.

**Actual behavior:** I was only able to publish a new repository.

**Reproduces how often:** 100% of the time.

### Logs

[2017-07-21.kactus.production.txt](https://github.com/kactus-io/kactus/files/1166748/2017-07-21.kactus.production.txt)

**Comment by mathieudutour** [comment]
not sure I understand:
1) you have a public repository that you want to transform into a private one?
2) you have an existing private repository, you started another repository and now you want to push the new repository to the existing one?

**Comment by mwagz** [comment]
Sorry. I have a private repository on Github. I would like to tell Kactus to push to that repository. #2 more closely resembles the issue I'm having.

**Comment by mathieudutour** [comment]
if you go to Repository > Repository Settings, you can change the remote url

**Comment by mwagz** [comment]
Ok. I see that, but in order to see that, I have to first publish to a repo and then switch. Is it possible to either enter an existing repo or publish to a new one?

**Comment by mathieudutour** [comment]
so if it's an existing repo with some stuff inside already, you will need to clone it first. Then you can copy paste your changes inside and push then
