### ISSUE TITLE
File generated can not be opened by Sketch

### ISSUE THREAD

**Issue by hebertialmeida** [kactus-io/kactus#32]
### Description

The file generated by Kactus is not opening on Sketch. Seems that the "Export Sketch File" is working, but when I remove the file created by Sketch and do the "Regenerate Sketch File" it is not opening.

### Version

**Kactus version:** 0.1.12

**OS version:** 10.12.5

### Steps to Reproduce

I have pushed the design here: https://github.com/Adventech/design

1.  Open Kactus and "Regenerate Sketch File";
2. Try to open the generated file.

**Expected behavior:** Open the generated file on Sketch

**Actual behavior:** Cannot open the file

**Reproduces how often:** Always

**UPDATE**
I have also tried with **Kactus version:** 0.1.13, now it is not even generating the Sketch file.

**Comment by mathieudutour** [comment]
do you still have your sketch file initial? Remove the `Adventech-site` folder, copy your sketch file again and it should work

**Comment by hebertialmeida** [comment]
Yes, I have it, when I add it to repo seems that it parses again and update the json files. But in this new version seems that there is a bug generating sketch file.

![regenerate mov](https://user-images.githubusercontent.com/103670/28555651-3a9c8dae-70cf-11e7-8420-bcffa2ee5f54.gif)

**Comment by mathieudutour** [comment]
can you send me the sketch file?

**Comment by hebertialmeida** [comment]
Here it is: https://www.dropbox.com/s/y9pjxu7pyzez0dp/Adventech-site.sketch?dl=0

**Comment by mathieudutour** [comment]
found the bug, thanks. It's deploying, the new version should be there soon

**Comment by hebertialmeida** [comment]
Thanks! I will try..

**Comment by hebertialmeida** [comment]
Seems that the generation is fixed but only if the existing Sketch file is there, if there is not sketch file it is not generating for me a new one.

**Comment by mathieudutour** [comment]
yes there was a error where it didn't save the images. So the files that you had couldn't re-generate the sketch file
