### ISSUE TITLE
Ask to locate Sketch when not found

### ISSUE THREAD

**Issue by vverhoek** [kactus-io/kactus#34]
### Description

Kactus mentions he cannot find Sketch, but I have Sketch and can even create Sketch files (even starting from Kactus). I assume that is the reason why I don't see the changes in a visual (only code)

### Version

**Kactus version:** 0.1.14

**OS version:** 10.12.5

### Steps to Reproduce

1. Install Kactus
2. Open Kactus
3. Message Bottom Left corner: Kactus needs Sketch to function properly and we couldn't find it.
4. Create repository
5. Create Sketch file
6. Save changes
7. Commit changes
8. Changes are registered, but not support by a visual 

**Expected behavior:** I expect to see a a visual to be able to compare the changes

**Actual behavior:** There is no visual only text

**Reproduces how often:** 100% (after reinstalling Sketch and Kactus a couple of times)

**Comment by mathieudutour** [comment]
What is the path to Sketch?

**Comment by vverhoek** [comment]
thanks for the quick reply. I noticed that the application was called Sketch-3 and not just Sketch (because I downloaded it a couple of times). That was the problem. Sorry...

**Comment by mathieudutour** [comment]
No worries. I should probably ask to locate Sketch if not found

**Comment by mathieudutour** [comment]
fixed in https://github.com/kactus-io/kactus/commit/54e384c2477d2ad8b8ac104b97cabbb357d68900
