### ISSUE TITLE
Just paid for full access but still seeing prompt to subscribe whenever i try to fetch

### ISSUE THREAD

**Issue by H3GGERS** [kactus-io/kactus#35]
### Description

[Description of the issue]

### Version

**Kactus version:** [version here]

**OS version:** [version here]

### Steps to Reproduce

1. [First step]
1. [Second step]
1. [and so on]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Reproduces how often:** [What percentage of the time does it reproduce?]

**Comment by mathieudutour** [comment]
The payment failed. Following up by email.
