### ISSUE TITLE
Slow to recognize changed files

### ISSUE THREAD

**Issue by hungrysquirrel** [kactus-io/kactus#37]
### Description

After making a handful of changes the Kactus does not show a list of changed files. If I go to iTerm and do a `git status` and see a long list of changed files. Sometimes the Kactus GUI catches up...other times it does not or...it loads a partial list and I make a commit only to find it did not finish indexing the changed files.

### Version

**Kactus version:** 0.1.15

**OS version:** 10.12.5

### Steps to Reproduce

1. Make changes to Sketch file
1. Go back to Kactus to see changes
1. Wait for 5+ minutes, or use iTerm to see `git status`
1. Sometimes Kactus loads a complete change list, other times it's incomplete and files get left out of the commit and I need to "amend" the commit.

**Expected behavior:** I would expect some status or progress indicator to show me Kactus is still indexing a list of changes. I would expect Kactus to poll for changes more often.

**Actual behavior:** Kactus either missed changes all together or loads an incomplete list.

**Reproduces how often:** 90%

### Logs

[2017-07-31.kactus.production.log.zip](https://github.com/kactus-io/kactus/files/1189181/2017-07-31.kactus.production.log.zip)

**Comment by mathieudutour** [comment]
hum it tries to get the status every time it get focused.

it looks like there were a tons of files (which can totally happen with a big sketch file):
`git status --untracked-files=all --branch --porcelain=2 -z (took 71.095s)`

I'll try to think of a solution

**Comment by mathieudutour** [comment]
actually, could you send me such a big file?

**Comment by hungrysquirrel** [comment]
@mathieudutour I can't send you the Sketch file referenced in that log file but I can send something similar. I will email you a file that has similar complexity. Thank you for looking at this issue.

**Comment by mathieudutour** [comment]
I just published a new version of Kactus with a loading indicator. I haven't been able to reproduce a `git status` taking more than a minute but I have a very high-end MBP so it might be why.

Hope that makes it easier to see when there is an activity.

**Comment by hungrysquirrel** [comment]
@mathieudutour The indicator is a great improvement. Keeps me form committing my changes until I know all file changes have been loaded. Thank you!

**Comment by hungrysquirrel** [comment]
Well I may have spoken too soon. I saw the indicator spinning and then it stopped but the list of changed files did not update. I have a fairly decent MBP too. 

Any advice?

**Comment by mathieudutour** [comment]
Hum not sure. I'll continue to look into it

**Comment by mathieudutour** [comment]
I added another indicator to show that git is doing something (previously it was only to show the parsing the sketch files).

Don't think I can do anything more for now. But will keep in mind performance
