### ISSUE TITLE
I keep getting error of binary files changed "error: Your local changes to the following files would be overwritten by checkout:"

### ISSUE THREAD

**Issue by debayangojek** [kactus-io/kactus#40]
### Description

[Description of the issue]

### Version

**Kactus version:** [version here]

**OS version:** [version here]

### Steps to Reproduce

1. [First step]
1. [Second step]
1. [and so on]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Reproduces how often:** [What percentage of the time does it reproduce?]

**Comment by mathieudutour** [comment]
Hum not sure what this is, not a lot of info but if I had to guess, I'd say that you need to add `*.sketch` in your `.gitignore`
