### ISSUE TITLE
Error in creating new sketch file

### ISSUE THREAD

**Issue by yoneth** [kactus-io/kactus#43]
I've got an error while creating new sketch file with shared styles

**Comment by vverhoek** [comment]
I might have the same issue. It can not find/open the sketch file anymore, since I have shared a page and styles. I thought it had to do with me, because I am testing out a lot.

**Comment by mathieudutour** [comment]
Should be fixed in version 0.2.2 (which is deploying right now).

@yoneth your set would still fail because your shared page uses symbols that are on another page. So you need to share both
