### ISSUE TITLE
Creating a new sketch file within Kactus, fails when including /

### ISSUE THREAD

**Issue by absentees** [kactus-io/kactus#44]
### Description

Kactus does not allow a user to create a new Sketch file with a / character in the Name. Must be using `/` in the path of the file.

### Version

**Kactus version:** 0.2.2

**OS version:** Mac OS 10.12.5

### Steps to Reproduce

1. Click the plus
2. Enter a name with a `/` in it, like `something / this`
3. `ENOENT: No such file or directory`

**Comment by mathieudutour** [comment]
good point, it should create the folders automatically

**Comment by mathieudutour** [comment]
fixed in 0.2.4
