### ISSUE TITLE
Clone a repository from my own organization, authenticate fail.

### ISSUE THREAD

**Issue by Steven0811** [kactus-io/kactus#46]
### Description

I'm trying to clone a repository from my own organization, and change my Sketch file.

However, I commit it, when I want push origin, Kactus prompt up a window, It told me that Kactus can't authenticate my Github account ,  I've reenter my username and password, still fails.

This is a public repository, am I missed something? or this feature is for Premium?
![screen shot 2017-08-14 at 5 09 10 pm](https://user-images.githubusercontent.com/4948562/29265334-4ef6536c-8113-11e7-9b96-d334304a20fe.png)

### Version

**Kactus version:** 0.2.2

**OS version:** macOS 10.13 beta 5

### Steps to Reproduce

1. Clone a organization repository.
2. Drag my file into repository folder.
3. Commit change.
4. Publish branch.
5. Get some authenticate error.

**Comment by mathieudutour** [comment]
Hum it should work. Are you certain your user has write-access to the repo?

**Comment by Steven0811** [comment]
@mathieudutour Yes, the repo and organization are I created, I'm very certain that I have permission to full-access.

**Comment by mathieudutour** [comment]
I saw that you managed to push here https://github.com/Steven0811/goodtogo_web_design. Is this still an issue?

**Comment by Steven0811** [comment]
I can't push to organization's repo, so I had to push my personal account repo. It's works fine.

**Comment by mathieudutour** [comment]
Hum that’s weird. Could you try logging out and login my in again using the web interface (not the username/password)? It should ask you for permissions to access your organisations

**Comment by Steven0811** [comment]
Version
Kactus version:  0.2.4
OS version: macOS 10.13 beta 6

I would like to do a full testament for you , so I downloaded the new version that you released few days ago,but after I downloaded it, this error messages keeps coming out. 😢😢😢

![screen shot 2017-08-22 at 12 25 48 pm](https://user-images.githubusercontent.com/4948562/29549282-df9f60d0-8739-11e7-930a-2fb9d1aac99a.png)

**Comment by mathieudutour** [comment]
yeah sorry about that, the new version should fix it (#49)

**Comment by mathieudutour** [comment]
Could you check that you granted the right for kactus to access the organization here: https://github.com/settings/connections/applications/9162b5db386de47692b3 ? There should be a green tick. Otherwise, click on "grant".

**Comment by Steven0811** [comment]
oh, It's seems like this problem has been solved, very appreciate. 🎉
