### ISSUE TITLE
Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by LumpyLi** [kactus-io/kactus#49]
### Description

When I clone repo from GitHub and use Kactus to open it, shows the **Cannot read property 'split' of undefined** alert.

### Version

**Kactus version:** 0.2.4

**OS version:** 10.12.6 (16G29)

### Steps to Reproduce

1. Clone Repository from GitHub in Kactus
1. Create a Sketch file in Kactus
1. Kactus shows the **ERROR ALERT**

![2017-08-21 5 48 03](https://user-images.githubusercontent.com/8208675/29514112-eef3b0c2-8699-11e7-8a3d-72fcb8b4b2af.png)

**Comment by jperals** [comment]
I am also getting this error.

It seems to happen when I create a new Sketch file or move an existing Sketch file into the repo directory with Finder. Once that happens, then the "Regenerate Sketch File" button and the "Export Sketch File" buttons also trigger this message and don't seem to do their job. Also every time I focus on the app window the error message pops up. The "Open in Sketch" button however works.

I am using the development version (cloned with Git and started from the command line with `npm start`) and when this happens the last debug message on the terminal always seems to be:

```
debug: [ui] Executing getAuthorIdentity: git var GIT_AUTHOR_IDENT
```

Initially I was not logged in to Github, but then I logged in and this didn't seem to fix it, I still have this problem. Also my user information in the "Git" tab in Kactus' Preferences window looks right...

**Comment by jperals** [comment]
I think I finally narrowed it down: it seems to be related with the `.gitignore` file not being present.

**Comment by herkulano** [comment]
@jperals added a `.gitignore` but the problem remains.

**Comment by mathieudutour** [comment]
Sorry I don’t have access to my laptop right now. Is there a stack trace in the logs?

**Comment by jperals** [comment]
@herkulano But does the `.gitignore` file contain a line with `*.sketch`? I think that is the issue. Kactus generates a `.gitignore` with that content, but if for some reason you mess with it and remove it then this problem appears.

So this is probably not top priority as we could say that this is not a main use case, but still Kactus could be made a bit more robust by handling this in a better way, I guess?

**Comment by jperals** [comment]
Well, as this can happen not only when messing with the `.gitignore` but when cloning an existing repo I guess this is indeed important. (But this is of course for @mathieudutour to decide)

**Comment by mathieudutour** [comment]
Yeah definitely need to fix this. I’m on holiday this week, will look at it on Monday.

**Comment by davidmead-dt** [comment]
We've suddenly had this issue today. Been fine before.

Our `.gitignore` files are in place. So I have no idea how to work around it. Means we can use Kactus for the time being. I did see that Sketch did an update too.

**Comment by tiptronic** [comment]
same thing as @davidmead-dt (using 0.2.4 and Sketch 46.2)

**Comment by tiptronic** [comment]
...btw 0.2.2 works fine

**Comment by tiptronic** [comment]
0.2.3 too

**Comment by mathieudutour** [comment]
I'm deploying a new version (0.2.5) which should fix this. Please tell me if not
