### ISSUE TITLE
Help > Show User Guides shows help for GitHub Desktop

### ISSUE THREAD

**Issue by aparajita** [kactus-io/kactus#50]
### Version

**Kactus version:** 0.2.4
**OS version:** 10.12.6

### Steps to Reproduce

1. Select Help > Show User Guides.
1. You end up here: https://help.github.com/desktop-beta/guides/

**Expected behavior:**

I expect to end up at https://kactus.io/help/

**Actual behavior:**

See above.

**Reproduces how often:**

Always.

**Comment by mathieudutour** [comment]
fixed in 0.2.5
