### ISSUE TITLE
`kactus import` reorders pages alphabetically

### ISSUE THREAD

**Issue by aparajita** [kactus-io/kactus#51]
### Version

**Kactus version:** 0.2.4
**OS version:** macOS 10.12.6

### Steps to Reproduce

1. Run `kactus parse` on a Sketch file with pages that are not sorted alphabetically.
1. Run `kactus import` on the result of `kactus parse`.

**Expected behavior:** Pages are restored in the original order.

**Actual behavior:** Pages are restored in alphabetical order.

**Reproduces how often:** Always

### Notes

From what I can see, `kactus parse` is not exporting the `pages` from `document.json`. That array tells you the order of the pages.

**Comment by mathieudutour** [comment]
that's a good point. What do you think should be the behavior for shared pages? Just put them at the beginning?

**Comment by aparajita** [comment]
Yes, I imagine putting shared pages at the beginning would be the best solution.

**Comment by aparajita** [comment]
Do you have an ETA on a fix for this? I'd like to use Kactus, but having to reorder my pages every time I commit is a no-go.

**Comment by mathieudutour** [comment]
Maybe tomorrow or the day after tomorrow

**Comment by mathieudutour** [comment]
fixed in https://github.com/kactus-io/kactus-cli/commit/f769e64da28a8fa3c1d7a19c38181bfb5c1d4063

Being deployed on 0.2.6
