### ISSUE TITLE
Cannot purchase license if not yet expired

### ISSUE THREAD

**Issue by alampros** [kactus-io/kactus#52]
### Description

If the trial period is not expired, there is no way to purchase a license. My trial expired, but my coworker's is not and we'd like to purchase licenses organization-wide all at once.

### Version

**Kactus version:** v0.2.4

**OS version:** macOS 10.12.6

### Steps to Reproduce

1. Download a fresh copy
2. Get out your credit card
3. Stare at it for a while
4. Put it back in your wallet
5. Do not profit

**Expected behavior:**
![we want to give you money!](http://i0.kym-cdn.com/photos/images/facebook/000/264/200/acb.jpg)

**Actual behavior:** We cannot give you money!

**Reproduces how often:** 100% during trial period, 0% after

#### Additional Information

Can't wait to get this integrated into our workflow – thanks so much for making this great tool!

**Comment by mathieudutour** [comment]
That's some issues that I like to see :)

I'll see what I can do for organization-wide licenses. For now, I can do it manually if you prefer 1 bill for multiple licenses

**Comment by alampros** [comment]
Looks like [v0.2.5](https://github.com/kactus-io/kactus/releases/tag/v0.2.5) addresses this (7b786d1fce86708f13988f7e71a97bc71fbb07ab). Thanks!
