### ISSUE TITLE
Sign in with GitHub Enterprise account does not work

### ISSUE THREAD

**Issue by konki-vienna** [kactus-io/kactus#56]
### Description

When I try to sign in with my companies GitHub Enterprise Account, I get two errors:
1. If I trie to sign in via "Sign in using your browser" a tab with a GitHub 404-page opens in the browser.
2. When I try to sign in via the Kactus-App itself, I get an error message telling me, that my GitHub Enterprise version is not up to date - which is not true, as we are using the latest available version (2.10.6).

### Version

**Kactus version:** 0.2.6

**OS version:** MacOS Sierra 10.12.6

### Steps to Reproduce

1. Click on "Publish Repository"
2. Click on Tab "Enterprise"
3. Click button "Sign In"
4. Enter enterprise server address
5. Enter username and password
6. Click button "Sign In"
7. Boom - Error Message 

**Expected behavior:** Would expect to be able to login

**Actual behavior:** Error message (see above)

**Reproduces how often:** 5 times

### Logs

2017-09-07T08:13:21.312Z - info: [ui] Stats reported.

**Comment by mathieudutour** [comment]
Hum the exact message is "Invalid OAuth application client_id or secret.". Does your enterprise version block third party apps?

**Comment by mathieudutour** [comment]
Maybe the application needs to be approved by an admin or something? (haven't used GitHub enterprise so I'm not sure what it looks like)

**Comment by konki-vienna** [comment]
No, we use a bunch of third party apps which have access to our repos. :(
Do you know of other kactus-users using github enterprise?

**Comment by mathieudutour** [comment]
I actually don't. I tried to look for differences that could exist between normal and enterprise GitHub for applications but couldn't find anything :/

**Comment by mathieudutour** [comment]
Could you tell me what's the URL that gives you the 404?

**Comment by konki-vienna** [comment]
https://mygithubenterprisedomain.at/login/oauth/authorize?client_id=9162b5db386de47692b3&scope=repo%20user&state=e0df9654-fa09-4893-80a8-7b1784c1662c

**Comment by konki-vienna** [comment]
I justed tried the other way around - I created a git project on our enterprise github and cloned it through/to kactus - now the login did work.

Did I get your pricing model right, that for enterprise Github Kactus will cost $11.99/Month?
Is this per team or per user?

**Comment by mathieudutour** [comment]
Hum that's really weird, the login is the same. Well, I'll continue to investigate a bit.

Yes, that's per user, same as GitHub.

**Comment by zyv** [comment]
@mathieudutour Sorry for hijacking this issue, but I read on the Kactus website that the $11.99 version supports any git server, not only GitHub. We are using BitBucket, and so I wanted to check it out, but I can't figure out how to pay you :) and where can I type BitBucket access data in. Hopefully the answer is a simple link that I have overlooked? Many thanks!

**Comment by mathieudutour** [comment]
When you clone a Repository, it will ask you for the url. Enter the bitbucket url and when you will try to push or pull, it will ask you for the bitbucket credentials and to pay to unlock Kactus

**Comment by mathieudutour** [comment]
So I've found the bottom of the issue. Github application doesn't work on GitHub Enterprise except for some GitHub owned application (like Github Desktop).

So you will need to create an application and add the client_id and client_secret in Kactus. I added some instructions about how to do so when there are needed.

shipping in 0.2.10 (deploying now)
