### ISSUE TITLE
Error in regeneration of sketch file

### ISSUE THREAD

**Issue by lucaorio** [kactus-io/kactus#58]
During regeneration, I get this error:

```
app-store.ts:143 Uncaught (in promise) SyntaxError: Unexpected token : in JSON at position 1070 at parse (<anonymous>)
```

The error points here:
```
const LastSelectedRepositoryIDKey = 'last-selected-repository-id'
```

It happens with pretty much all the `sketch` files of a specific project I'm working on. What could be the cause?

**Comment by mathieudutour** [comment]
hum the source maps are probably off, there is no way that there could be an error on that line haha.

is there a more helpful stack trace? Is the project open source, can I check it?

**Comment by lucaorio** [comment]
Hey @mathieudutour , apologies for the late reply. I've been quite overwhelmed at work.

Unfortunately I can't share the `sketch` file. The other day I started to delete a bunch of stuff and tried to commit again to understand what's causing the error, but it's going to be a tedious process :D

Is there any step that I can follow in order to provide a more helpful stack trace?

**Comment by mathieudutour** [comment]
if you go to View > Toggle Developer Tools, you should be able to see all the logs and stack traces
