### ISSUE TITLE
Changed File inspector checkboxes don't function as intended

### ISSUE THREAD

**Issue by reddolan** [kactus-io/kactus#69]
*Not sure if this is one issue or two. But I will outline the issues here*

### Description
Can tell if items items are being deselected in the Changed Files inspector

### Version
**Kactus version:** 0.2.13
**OS version:** 10.12.6

### Steps to Reproduce
1. make changes to a file or files
2. check in Kactus Changed File inspector
3. deselect the main checkbox
4. none of the files changing have their checkboxes deselected
5. selecting or deselecting any of the file checkboxes doesn't visibly deselect the file

![kactus-checkboxes](https://user-images.githubusercontent.com/1858226/32746722-5c62d3a0-c86b-11e7-8594-a91488e6398b.gif)

**Expected behavior:**
- deselect the main checkbox will deselect all files changing
- deselect any file in the Changed Files inspector would visibly change the checkbox to "deselected"

**Actual behavior:**
not files are visibly deselected, but are affected with committing changes. It seems like the checkbox selector just isn't visibly being updated

**Reproduces how often:** 100%

### Logs
[2017-11-13.kactus.production.log](https://github.com/kactus-io/kactus/files/1468350/2017-11-13.kactus.production.log)

**Comment by mathieudutour** [comment]
Thanks for the bug report. Should be fixed in 0.2.14 (deploying now)
