### ISSUE TITLE
Please provide an AppImage for download on GitHub Releases

### ISSUE THREAD

**Issue by probonopd** [kactus-io/kactus#71]
### Description

An [AppImage](https://appimage.org/) for Linux is currently not available for download on GitHub Releases

### Version

All

### Additional Information

As per

https://github.com/kactus-io/kactus/blob/e75ae08a96ceeb537517b9016968e6e0df3bb7d2/package.json#L133

kactus is already configured to be bundled as an AppImage. It would be great if you could provide an AppImage for download on [GitHub Releases](https://github.com/kactus-io/kactus/releases).

Providing an [AppImage](http://appimage.org/) would have, among others, these advantages:
- Applications packaged as an AppImage can run on many distributions (including Ubuntu, Fedora, openSUSE, CentOS, elementaryOS, Linux Mint, and others)
- One app = one file = super simple for users: just download one AppImage file, [make it executable](http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80), and run
- No unpacking or installation necessary
- No root needed
- No system libraries changed
- Works out of the box, no installation of runtimes needed
- Optional desktop integration with `appimaged`
- Optional binary delta updates, e.g., for continuous builds (only download the binary diff) using AppImageUpdate
- Can optionally GPG2-sign your AppImages (inside the file)
- Works on Live ISOs
- Can use the same AppImages when dual-booting multiple distributions
- Can be listed in the [AppImageHub](https://appimage.github.io/apps) central directory of available AppImages
- Can double as a self-extracting compressed archive with the `--appimage-extract` parameter

[Here is an overview](https://appimage.github.io/apps) of projects that are already distributing upstream-provided, official AppImages.

If you have questions, AppImage developers are on #AppImage on irc.freenode.net.

**Comment by mathieudutour** [comment]
sketch is not available on linux, why would you want to use kactus on linux?

**Comment by probonopd** [comment]
Hum, I don't even know what _sketch_ is but I definitely think Linux could need a "proper version control tool for designers" and since this is an Electron app I thought it was possible. If it is not, better remove 

https://github.com/kactus-io/kactus/blob/e75ae08a96ceeb537517b9016968e6e0df3bb7d2/package.json#L143-L146
