### ISSUE TITLE
Feature request: Install pre-commit hook option

### ISSUE THREAD

**Issue by alampros** [kactus-io/kactus#73]
It would be really nice if Kactus could install (and remove) a `pre-commit` hook in the repo to perform `kactus-cli.parseFile` on the sketch files.

I often do git operations in a terminal or other git GUI and forget to switch back to Kactus (after making some changes to my sketch file) before committing. This leaves my repo and my parsed sketch descriptors out of sync and I have to amend my commit after focusing Kactus (to trigger the parsing).

In theory, this could let me work with Sketch and terminal without needing to have Kactus open as well (at least until I need to compare or merge).

**Comment by mathieudutour** [comment]
It's unlikely that I will add this feature but it shouldn't be hard to add it for your repo if you already how git hooks works. Have a look here: https://github.com/kactus-io/kactus-cli :)
