### ISSUE TITLE
Error while Kactus scans my local git repo for changes

### ISSUE THREAD

**Issue by hungrysquirrel** [kactus-io/kactus#74]
### Description

When I launch Kactus it begins to scan my local git directory for changes. Within seconds it displays this error. I have not seen this before. My last commit was 9 hours prior. Changes since then have been adding a new Sketch file to the project and many text layer changes.

<img width="1115" alt="kactus" src="https://user-images.githubusercontent.com/232397/33462854-05e40422-d5ef-11e7-8be7-4d1a3f7d0546.png">

### Version
**Kactus version:** 0.3.0

The operating system you are running on may also help with reproducing the
issue:
**OS version:** Mac 10.12.6 (16G29)

### Steps to Reproduce

1. Made text layer changes, added a new Sketch file
1. Launch Kactus
1. Modal with error message opens up
1. Close modal, Kactus continues to scan for changes
1. Kactus locks and unlocks the UI as it scans changes (this always happens) making it very long process to type a commit message as UI freezes and thaws.

**Expected behavior:** Scan repo for changes and let me make a commit

**Actual behavior:** UI throws error message, freeze/thaw for 5-6 minutes before I can Commit.

**Reproduces how often:** Freeze/thaw...all the time. The error modal...1st time.

### Logs

[2017-12-01.kactus.production.log](https://github.com/kactus-io/kactus/files/1520043/2017-12-01.kactus.production.log)

**Comment by mathieudutour** [comment]
it should be fixed in v0.3.3. Feel free to re-open if that's not the case
