### ISSUE TITLE
Choosing "discard all changes" in Kactus it does not seem to work

### ISSUE THREAD

**Issue by JaseMiller** [kactus-io/kactus#75]
### Description

When attempting to switch branches in Kactus, it suddenly finds changes to some files on my local machine. When I choose "Discard All Changes" by ctrl-clicking the "changes" section heading, I get a warning (good idea) but clicking the "Discard Changes" button doesn't seem to do anything. The changes are still listed. Discarding them one by one also does not seem to work. I cannot change branches in this scenario unless I commit the changes I'd rather just discard.
  
### Version

**Kactus version:** 0.3.0

**OS version:** MacOS 10.12.6

### Steps to Reproduce

1. Have some changes appear in changes section of the app.
2. Ctrl-click on the "5 changed files" header area to show a contextual menu that reads "Discard All Changes..."
3. Choose "Discard All Changes..."
4. Read the warning modal that shows a green "Cancel" button and a white "Discard Changes" button.
5. Choose the Discard Changes button.
6. Nothing changes visually and I still cannot checkout a different branch.

**Expected behavior:** I'd expect the changes listed under "5 changed files" to disappear and that I would be able to switch branches again.

**Actual behavior:** I'm stuck on the same branch unless I commit the changes or remove the files using Finder and then commit the removals (not my preference).

**Reproduces how often:** Every time I try.

### Logs

Attached.
[2017-12-08.kactus.production.log](https://github.com/kactus-io/kactus/files/1563810/2017-12-08.kactus.production.log)

#### Additional Information

**Comment by mathieudutour** [comment]
hum I'm guessing it's because kactus exports the sketch file again so it's bringing back the changes. If you delete your sketch file, you should be able to discard the changes

**Comment by matteodesanti** [comment]
Same for us. Deleting alla sketch files does not work: Kactus seems to recreate all the files (both .sketch and the directory). Any news?

**Comment by JaseMiller** [comment]
For what it's worth, manually deleting the Sketch files from my repo and committing those changes seems to have resolved the immediate issue for me. That process seems to have added the specific files I deleted to the .gitignore, which is fine for me at the moment. 

I'm encountering some unusually slow behavior within Kactus now, but I'm not sure that's related (or even an issue with Kactus). Will open another issue if that seems to warrant it later.

**Comment by mathieudutour** [comment]
oh, it was because you were checking in the sketch files?

I'm trying to repro but if the sketch files are not checked in, it looks fine.

@matteodesanti, can you make sure that your .gitignore contains `*.sketch` and that your sketch files are not tracked?

**Comment by JaseMiller** [comment]
My `.gitignore` file has included `*.sketch` from the beginning but for some reason it was still trying to add those Sketch files to the repo. Those issues seem resolved for me now. Thanks. I am having some unusual issues with massive slow-down in Kactus showing huge amounts of changes (20,000+ of them) even if I just make a slight color change to one of my Sketch files. I added a comment in a possibly related issue earlier today.

**Comment by ericgraficode** [comment]
I'm having the same issue @JaseMiller described, discard changes doesn't work, and the changes are still reflected, I do have the *.sketch files ignored.

-Sketch 48.2
-Kactus 0.3.1

**Comment by mathieudutour** [comment]
Can I have a look at your repo?
