### ISSUE TITLE
Something in Kactus is changing all tracked JSON files upon starting the app

### ISSUE THREAD

**Issue by JaseMiller** [kactus-io/kactus#76]
### Description

I've tested why I keep getting thousands of changes even immediately after committing previous changes (even without opening the files in Sketch). I've narrowed it down to some issue when opening the Kactus app. The tracked directory in Finder shows no new modification dates. That's as it should be. Then opening Kactus suddenly changes all modification dates on JSON files in the tracked directory.

### Version

**Kactus version:** 0.3.0

**OS version:** MacOS 10.12.6

### Steps to Reproduce

1. Close Sketch and Kactus.
2. Note modification dates/times on directories with JSON files in tracked directory.
3. Wait a bit.
4. Open Kactus.
5. Note at first 0 changes display, but the directory in Finder shows modification dates on all JSON files that reflect the time Kactus was opened. Kactus begins to catch up in the GUI by showing those changes in the left column, eventually adding up to hundreds if not thousands of changes files.

**Expected behavior:** A clean repo with no changes should remain so until I modify something in Sketch, at which point Kactus should track that change. Otherwise it should show no local changes.

**Actual behavior:** Kactus seems to have modified JSON files in the tracked directory in some way.

**Reproduces how often:** 100%

### Logs

[2018-01-03.kactus.production.log](https://github.com/kactus-io/kactus/files/1601134/2018-01-03.kactus.production.log)

#### Additional Information

If I close Kactus the file modification stamp remains frozen as it should. Each time I open Kactus the date/time stamp changes on the modification date for those files.

**Comment by mathieudutour** [comment]
when you open Kactus, it exports all the sketch files of the repo to JSON (that's because I'm not keeping the list of sketch files and their modification timestamps). So yeah, the timestamps of the JSON files will change but if their content don't, it won't show as a change in git.

So i'd say that either:
- you made a change in the sketch file and when you reopen kactus, it gets sync
- it's because of #60

**Comment by JaseMiller** [comment]
Thanks, @mathieudutour. In my case, I'm not even opening those Sketch files and previous changes were already committed and pushed to the repo in GitHub via Kactus. So, maybe it's related to #60 but I'm not sure. For some reason, Kactus must be seeing the exported JSON files as changes to track in Git. Is there a way to dial that in, or is there maybe something with my configuration that got messed up and I should delete everything and rebase or start a new repo to see if that fixes it? Thx!

**Comment by mathieudutour** [comment]
could you show me an example of one of the changed file?

**Comment by JaseMiller** [comment]
Sure. I can make a snapshot of one of the JSON directories for a Sketch file and then open Kactus and take a new snapshot of it after Kactus has (allegedly) changed it. Maybe that will give a clue to the mystery...

**Comment by JaseMiller** [comment]
`test-tracking-1.zip` includes the very simple Sketch file and JSON directory generated by Kactus that has (technically) not been modified since 12/22/17.
`test-tracking-2.zip` includes the same files but after I reopened Kactus and it modified the change date on the JSON directory files (but not the Sketch file).

So NO real (Sketch based) changes have been made to this file between this.

[test-tracking-1.zip](https://github.com/kactus-io/kactus/files/1601402/test-tracking-1.zip)
[test-tracking-2.zip](https://github.com/kactus-io/kactus/files/1601401/test-tracking-2.zip)

I hope this provides some clues to what's going on. Thanks!

**Comment by mathieudutour** [comment]
the first one is empty?

anyhow, I'm pretty sure it's because of the text layers as in #60. If you look at the text diff in Kactus, it should show only `_archive` fields changes.

**Comment by JaseMiller** [comment]
OK. I'll take a look. Yea, that first one was empty. Going to redo the process and see if that's the case again, or if I did something wrong archiving the file...

**Comment by JaseMiller** [comment]
I did something wrong earlier with the archiving. Here are the two directories to compare. Neither should be empty. Thanks.
[test-tracking-2a.zip](https://github.com/kactus-io/kactus/files/1601587/test-tracking-2a.zip)
[test-tracking-1a.zip](https://github.com/kactus-io/kactus/files/1601588/test-tracking-1a.zip)

**Comment by JaseMiller** [comment]
BTW, I think this is related... Kactus seems to be increasing changes in the tracked directory exponentially. Last week it was showing around 900 changes when I opened Kactus, earlier this week it was reading 23,000, and now it's showing over 32,000 changes to commit in the directory. The only time this goes down to zero changes is when I leave Kactus running and commit and push all changes via CLI. Kactus then fetches the branch from GitHub and reads zero changes locally. Once I quit Kactus and reopen the app, it starts exponentially counting changes again, even if I didn't open anything in Sketch.

**Comment by JaseMiller** [comment]
@mathieudutour Hang on... I think I may have found the problem and fixed it... will post a follow up here...

**Comment by JaseMiller** [comment]
I discovered a conflict in my `.gitignore` file. Understandably, `git` and therefore Kactus had trouble interpreting that in a useful way. Not sure how that happened or why I missed that, but I've fixed the file and am now retesting Kactus...

It started out promising with zero changes, but it's now reading 31,000+ changes and hanging. I'll update further if anything changes for better or worse.

**Comment by JaseMiller** [comment]
Alas, still experiencing essentially the same issues thought I've fixed the `.gitignore`. Checking for other *missed* conflicts etc. on my end...

**Comment by JaseMiller** [comment]
I'm noticing that in these large (30,000+) lists of changed JSON files, line 4 is consistently being changed. Below is an example. I'm not sure if this is expected behavior from Kactus or if these changes are what's causing `git` to flag it as a changed file (even though it hasn't been opened in Sketch).

```
-  "do_objectID": "909B1BD2-B071-4465-93AB-499FF8882B58",
+  "do_objectID": "622C740C-3E88-4562-968C-B7565921077D",
```

**Comment by mathieudutour** [comment]
wait the `do_objectID` is changing?? Does the filename change as well? It's supposed to be the do_objectID

**Comment by JaseMiller** [comment]
File names are not changing as far as I can see. Let me be clearer... In the Finder directory and in GitHub the filenames remain constant. If there's a `filename` variable somewhere I should look for, point me in that direction as I'm not seeing one at present. Thx!

**Comment by mathieudutour** [comment]
no, it is indeed the name of the file. So in some cases, the name of the file is different from the `do_objectID`?

**Comment by JaseMiller** [comment]
This may be of interest perhaps... The filename in GitHub is this:
```
ux-design-kit/sketch/flow/flow-mobile-reviews/Combining Mobile and Desktop Reviews/04AD4A21-9DF6-445A-8FE0-D0DFCC9D0127/0174D174-4273-4E49-8BFF-BCDE1A737F0F/C526A757-D501-4A3D-9303-00FBAB5020F1/B9D95558-8D10-4257-8211-A1F8876FF377/FA3EA97B-1BAB-4D99-BA17-7D4B175B5470/622C740C-3E88-4562-968C-B7565921077D.json
```
and the `do_objectID` for that file is this: `622C740C-3E88-4562-968C-B7565921077D`

**Comment by mathieudutour** [comment]
😱 that's so weird. But it is interesting indeed, I'll dig in this direction, thanks

**Comment by JaseMiller** [comment]
Thank YOU. :) I really appreciate what Kactus can do for our team.

**Comment by mathieudutour** [comment]
oh wait no, that's the right filename: `622C740C-3E88-4562-968C-B7565921077D.json`, i didn't scroll far enough -_-'

Do you have the repo somewhere so that I can have a look?

**Comment by JaseMiller** [comment]
Sure. [https://github.com/JaseMiller/ux-design-kit](https://github.com/JaseMiller/ux-design-kit)

**Comment by mathieudutour** [comment]
haven't looked at it yet but there are still some sketch files: https://github.com/JaseMiller/ux-design-kit/blob/master/sketch/flow/flow-business-login.sketch

**Comment by mathieudutour** [comment]
Yeah I'm positive it's because of the sketch files that are checked in. Delete them and commit manually, you should be good to go afterwards.

Regarding the sync when opening Kactus, I am now storing the modification date of the files so it shouldn't happen anymore :tada:

**Comment by JaseMiller** [comment]
So strange. I'll try adding that one to my `.gitignore` as well but am currently having trouble committing the proliferation of changes, so may not work for awhile. I had `*.sketch` in the `.gitignore` but then changed it to `sketch/*.sketch` in case that made a helpful difference since that the directory I put all my Sketch files into in this repo. My understanding is that either should work essentially the same in this particular case.

**Comment by mathieudutour** [comment]
it does work but if some files are already tracked, *ignoring* them isn't going to *remove* them
