### ISSUE TITLE
Suggestion: Enable support to GitLab and BitBucket

### ISSUE THREAD

**Issue by matteozambon89** [kactus-io/kactus#79]
For what I saw testing this app is strictly related to GitHub, it would be nice to support different providers such as GitLab and BitBucket.

**Comment by mathieudutour** [comment]
It's already support, just clone an existing repo from Gitlab or Bitbucket

**Comment by zmnv** [comment]
I have a local server with **GitLab**

I don't want to use GitHub at all.

Trying to Publish repo to Git**Lab**, but kaktus asks me to login and buy Git_Hub_ Enterprise account.. I don't wanna that account at all...

There are the way to use Kaktus with GitLab without GitHub?...

**Comment by mathieudutour** [comment]
No, it's asking you to login with GitHub because that's how Kactus manages account (like it could ask you to login with facebook or whatever). Then it's asking you to buy a _kactus_ enterprise license.

**Comment by zmnv** [comment]
😔 Sad, boring... 
But, maybe justly... 

Thanks anyway.

**Comment by mathieudutour** [comment]
Not sure what you mean.

Are you upset that you need to login with GitHub or that you need to buy a license?

If the latter:
> Why are you charging money for private use?
>
> We are independent developers and we'd like to support ourselves and the project long term. Commercial support, additional features, bug fixes and feature priority are provided with the Premium/Enterprise license, as well as ensuring the project stays alive.

**Comment by stefanmvc** [comment]
@mathieudutour Nope i gues zmnv meant the pain with github accounts, especially when github doesn't support sketch files previews so nobody is actually using github as a git for sketch files imo

**Comment by mathieudutour** [comment]
you don't need to use GitHub, just need to login with it. It's like login with facebook but instead of facebook it's github.
