### ISSUE TITLE
Connecting to Enterprise BitBucket

### ISSUE THREAD

**Issue by erikphanson** [kactus-io/kactus#80]
### Description

Trying to leverage Kactus for our corporate BitBucket account. I have it connected to the repository, when I try to push, it asks for either a personal GitHub or Enterprise GitHub account, since we're using a corporate BitBucket, I don't know how to proceed. None of the GitHub Enterprise fields match what I use to connect.
### Version

**Kactus version:** 0.3.1

**OS version:**10.12.3 (16D32)

### Steps to Reproduce

Attempt to publish to a branch

**Expected behavior:** I expect Kactus to ask for money, then allow me to push.

**Actual behavior:** Asks for an account that I don't have.

**Reproduces how often:** [What percentage of the time does it reproduce?]

**Comment by mathieudutour** [comment]
Kactus uses Github as an account system. It won't push to GitHub, it's just so that I can know who you are. It will then ask for the license (linked to the GitHub account) once logged in

**Comment by saschaeggi** [comment]
@mathieudutour we do have the same problem over here. We're using a corporate BitBucket account, so I am also interested in when the new payment way is rolled out
Thanks

**Comment by mathieudutour** [comment]
You can already use a bitbucket repo, but you still a github account as it is what Kactus uses for authentication

**Comment by saschaeggi** [comment]
@mathieudutour and when will be the new licensing be ready?

> I will roll out a way to pay for multiple license at once but it's not ready yet

**Comment by stefanmvc** [comment]
Any update? I want to create some enterprise/group account for kactus to pay for multiple lienses at one

**Comment by stefanmvc** [comment]
@mathieudutour

**Comment by mathieudutour** [comment]
It's done, sorry for not updating here: https://kactus.io/org/

**Comment by stefanmvc** [comment]
Yeah but it does not work for me, there was an endless loader of something. And what if I already have an enterprise license on my account and want to buy more seats?

**Comment by mathieudutour** [comment]
That's probably a bug then. Is there something in the console?
