### ISSUE TITLE
Not Seeing How to Commit Changes Pulled

### ISSUE THREAD

**Issue by erikphanson** [kactus-io/kactus#81]
### Description

Testing things out with a team member and we're new to Git, so maybe we're doing something wrong here. I had a repository going that he was able to add to Kactus and pull down the Master. To test, he changed some text, committed and pushed to origin. I then fetched, thinking it would pull own and allow me to see and accept the changes. I see that there are changed files but I can't see how to accept them. If I commit to master, that accepts the changes, but then my team member gets in the same situation. It seems like it ends up in this strange commit loop.
![screen shot 2018-01-22 at 2 53 49 pm](https://user-images.githubusercontent.com/2135857/35248726-130e35dc-ff84-11e7-968a-f29e95b8582b.png)

Also, it seems to still be tracking the .sketch file even though I've verified that it's in the ignore file - at least it is in the repository settings.

![screen shot 2018-01-22 at 2 47 05 pm](https://user-images.githubusercontent.com/2135857/35248485-23395528-ff83-11e7-9ba1-7d325649856e.png)

### Version

**Kactus version:** 0.3.1

**OS version:** 10.12.3 (16D32)

### Steps to Reproduce

1. Fetch a change from origin
2. See changed files
3. Not sure what to do here to not end up in a commit loop bouncing back and forth between team members.

**Expected behavior:** I would expect that when I pull from the origin I would be able to see the changes and accept them, which would make my local master the same as the origin master so I wouldn't have to do a separate commit that then wants me to push to origin. 

**Actual behavior:** I fetch from origin, I see the changes. Only way I can see to accept those change is to commit them, which then informs me I can push to origin.

**Reproduces how often:** [What percentage of the time does it reproduce?]

#### Additional Information

Forgive me if I'm misunderstanding how this works, but it seems if I accept the origin master, it shouldn't ask me to push that right back to origin, I should just me able to accept the changes into my local master which would then match to origin master.

**Comment by mathieudutour** [comment]
There is a couple of things:
- the sketch file is there because even tho the gitignore specify them, it was probably tracked before. So fix this, you will need to open your terminal in the Repo, and type `rm smart-compliance-atoms.sketch && git add smart-compliance-atoms.sketch && git commit -m 'remove sketch file from git' && git push'. That should fix this issue.
- when you colleague push to the origin master and that you pull, you don't get to "accept" the changes, it's already done. You can see his commits in the "History" tab. That's why we usually use "branches": https://kactus.io/help/how-to/

Hope that helps

**Comment by mathieudutour** [comment]
As a side note, git might have a steep learning curve but once you start to get your head around it, it's super powerful and you can't imagine doing things without :)

**Comment by erikphanson** [comment]
Thanks for the help, I appreciate it. Just to follow up, when I pull from origin, I'll see the changes compared to what they were on my local - if any - but I do not need to accept them? Seeing these checkboxes in "Changes" makes me think I need to do something.
![screen shot 2018-01-23 at 6 57 19 am](https://user-images.githubusercontent.com/2135857/35282577-aa9b043a-000a-11e8-947a-4e92a212cfa0.png)

**Comment by mathieudutour** [comment]
no you don't need to do anything. It's just that Kactus noticed some changes when it tried to re-export the file after pulling. Probably because you are not using the exact same Sketch version.
I'll try to see if I can fix that small change that is often appearing. But it's minor.
