### ISSUE TITLE
Standalone Kactus Client Package

### ISSUE THREAD

**Issue by MrLoh** [kactus-io/kactus#82]
First of all thank you for Kactus, it is a really great step in bringing git version control to design. 

I am a developer and designer and we are using a monorepo in our company that contains code for app, backend, etc. including the design files. While the Kactus App is pretty nice, it is getting really slow in such a big git repo with so many files. Also I am used to just use the comand line tools to manage my git, so I don't really care about the UI for the most parts. 

It would be really nice if I could simply install a kactus client via npm in my repository and than have a script to serialize my sketch files when needed, just like one would use gulp. Is something like that already possible in some way, or is it something you would consider supporting in the future. Maybe I could also help with something like that. 

Making Kactus available as a cli, could also help in establishing it as a standard for serializing sketch files and would sit great with your plans for sketch component packages.

**Comment by mathieudutour** [comment]
have a look at https://github.com/kactus-io/kactus-cli, you should find what you need
