### ISSUE TITLE
Authentication error when trying to push to origin

### ISSUE THREAD

**Issue by dvenprasad** [kactus-io/kactus#83]
### Description

When I am trying to push changes via Kactus to repository, I get an authentication error. 

I am able to push to via GitHub. I have double checked the account information and permissions and they all seem to be fine. 

This is only a problem when I try to push to a repository where I am not the primary owner. It works when I push to my own repositories. 

### Version

**Kactus version:** 0.3.1

**OS version:** MacOS 10.12.6

### Steps to Reproduce

1. Clone https://github.com/AlexsLemonade/refinebio-design.git
2. Make a change in repo 
1. Commit and push

**Expected behavior:** The push is successful.

**Actual behavior:**

![screen shot 2018-02-16 at 11 16 13 am](https://user-images.githubusercontent.com/15315514/36317363-e37e8cbe-130a-11e8-8f6e-ca8747579324.png)

**Reproduces how often:** 100%

### Logs
[2018-02-16.kactus.production.log](https://github.com/kactus-io/kactus/files/1732013/2018-02-16.kactus.production.log)

**Comment by mathieudutour** [comment]
You probably haven't given Kactus the permission to access the repo. Have a look here: https://github.com/settings/connections/applications/9162b5db386de47692b3, you should be able to "grant" or "request" the permission
