### ISSUE TITLE
Cannot See the Sketch Plugin of Kactus

### ISSUE THREAD

**Issue by StudioMastro** [kactus-io/kactus#84]
### Description

Hi on my MBP I cannot see the Kactus plugin in Sketch. What am I doing wrong?
### Version

**Kactus version:** [0.3.1]

**OS version:** [MacOs High Sierra]

### Steps to Reproduce

1. [First step]
1. [Second step]
1. [and so on]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Reproduces how often:** [What percentage of the time does it reproduce?]

**Comment by mathieudutour** [comment]
I couldn't repro.

Did you perhaps move kactus after opening it once? Could you go on `Sketch > Plugins > Manage plugins > Reveal Plugins folder` and see if there is a `kactus.sketchplugin` and if so, where it is pointing to? If it's there, you can probably just delete it. Opening Kactus will re-install it

**Comment by StudioMastro** [comment]
HI,
I did as you said and the alias for kactus.sketchplugin was there but pointing to a wrong path. Not sure what happened and why it went broke. Anyway I've uninstall and re-install and everything went back to its place. All working now. Thanks for your quick help.
Alessandro Mastrogiacomo

On Feb 22, 2018, at 04:10 PM, Mathieu Dutour <notifications@github.com> wrote:

I couldn't repro.

Did you perhaps move kactus after opening it once? Could you go on Sketch > Plugins > Manage plugins > Reveal Plugins folder and see if there is a kactus.sketchplugin and if so, where it is pointing to? If it's there, you can probably just delete it. Opening Kactus will re-install it
