### ISSUE TITLE
Publish branch button is not clickable, not able to push

### ISSUE THREAD

**Issue by timyaodpc** [kactus-io/kactus#85]
### Description

After commit new changes, the "Publish branch" button is not showing the upload icon, when I click the "Publish branch" button, it has no response, not clickable.

### Version

**Kactus version:** [0.3.1]

**OS version:** [10.12.6]

### Steps to Reproduce

1. [Clone my github private repo]
2. [Add a new sketch file and commit it]
3. [Click "Publish branch", it won't work]
4. [Go to my terminal, use `git push` is able to push to github.]

**Expected behavior:** [Click the "Publish branch" should push to remote repo]

**Actual behavior:** [Click the "Publish branch", nothing happen]

**Reproduces how often:** [always]

#### Additional Information
It works in my public repo, but not work for private repo.

**Comment by mathieudutour** [comment]
is it your private repo or the one of an organization?

**Comment by timyaodpc** [comment]
Hi @mathieudutour Thanks for your property response. We are paid account(about 5 accounts) and we are using github organisation and it's private repo under the organisation.
I check the log, it shows below details:
```
2018-02-23T00:56:02.503Z - warn: [ui] fetchRepository: '{{ my repo name }}' returned a 404
2018-02-23T00:56:06.988Z - warn: [ui] fetchRepository: '{{ my repo name }}' returned a 404
2018-02-23T00:56:06.989Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: {{ my repo name }} - {{ my github user name }} (has token)
```

**Comment by mathieudutour** [comment]
You probably haven't given Kactus the permission to access the repo. Have a look here: https://github.com/settings/connections/applications/9162b5db386de47692b3, you should be able to "grant" or "request" the permission To access the organisation
