### ISSUE TITLE
Buffersize limit

### ISSUE THREAD

**Issue by hungrysquirrel** [kactus-io/kactus#89]
## Description
The output from the command could not fit into the allocated stdout buffer. Set options.maxBuffer to a larger value than 10485760 bytes

How/Where can I make the requested change?

## Version
0.3.3
* Kactus:

* Operating system:
Mac OS High Sierra 10.13.3

## Steps to Reproduce
1. Start Kactus
2. Message appears

### Expected Behavior
Start Kactus and let it poll for changes to repo so I can commit and push etc.

### Actual Behavior
Kactus does not finish polling changes. Asks me to "The output from the command could not fit into the allocated stdout buffer. Set options.maxBuffer to a larger value than 10485760 bytes"

### Logs
[2018-03-12.kactus.production.log](https://github.com/kactus-io/kactus/files/1803720/2018-03-12.kactus.production.log)

### Screenshot
<img width="1280" alt="screen shot 2018-03-12 at 9 41 46 am" src="https://user-images.githubusercontent.com/232397/37297437-f3dddd7a-25da-11e8-8c7e-827f7c409f29.png">

**Comment by mathieudutour** [comment]
Is the repo open source?

The logs looks ok, the git status and the kactus status both finishes in 2s

**Comment by hungrysquirrel** [comment]
@mathieudutour The repo is not OpenSource.

**Comment by mathieudutour** [comment]
hard to say... Could you run `git status` in your terminal (after cd into your repo) and paste the result here?

**Comment by hungrysquirrel** [comment]
@mathieudutour Sent a gist directly to you...thank you for the support!
