### ISSUE TITLE
Merge issues

### ISSUE THREAD

**Issue by nguyendqnhu** [kactus-io/kactus#90]
## Version

* Kactus: 0.3.3

* Operating system: Mac OSX 10.13.3

### Expected Behavior

it to actually merge

### Actual Behavior

gets stuck on merge.

## Additional Information

git version 2.16.2

**Comment by nguyendqnhu** [comment]
[2018-03-14.kactus.production.log](https://github.com/kactus-io/kactus/files/1812076/2018-03-14.kactus.production.log)

**Comment by mathieudutour** [comment]
Not sure what you mean by "stuck" but I can see from the logs that there are some merge conflicts
