### ISSUE TITLE
Needs a way to notify broken sketch folder

### ISSUE THREAD

**Issue by synthresin** [kactus-io/kactus#92]
## Description

Sometimes, generated folder is broken while using Kactus (though it is not the scope of this issue)
When this happens, There is no notification that the folder is broken when I regenerate the sketch file.
It leads for user to committing further not knowing the folder is broken & making harder to fix as time goes.

## Version
0.3.3

* Kactus:
* Operating system:  Mac

## Steps to Reproduce
make a sketch folder that is broken and cannot be opened with sketch when converted to `.sketch` file.
and click `Regenerate Sketch File`.

### Expected Behavior
There should be some alert that notifies the sketch folder is broken.

### Actual Behavior
There's no error & user doesn't know there are some issues with generated folder & past commits.

## Additional Information
I think broken folder after committing & merging is also a critical issue. but I cannot reproduce it.

### Logs

**Comment by mathieudutour** [comment]
So the thing is: a folder might have the right structure but Sketch might not want to open it because the information it contains might be corrupted. It's pretty hard (like I don't see a way to do it right now) to know if a folder is broken.

But I agree that it shouldn't ever happen. So I'm interested in fixing the case where it broke if you manage to reproduce it :)

**Comment by synthresin** [comment]
I'll take a look if I can reproduce broken folder structure If I revert to specific commit. though It can be picky to share the commits because the sketch file is owned by my company.

**Comment by synthresin** [comment]
I found that the broken folder structure is reproduced when I hard-reset to specific commit. What do you to deal with the issue?

**Comment by synthresin** [comment]
One thing I miss : under the corrupted folder strucutre, `Regenerate Sketch File` button does nothing without error. In this case, if I manually do 'folder > zip > .sketch` process. the sketch file cannot be opened.

**Comment by mathieudutour** [comment]
Zipping the folder is not going to work, Sketch expect a single json file. That’s what Kactus is doing. 

Is there something written in the console when you try to regenerate the file? ()

**Comment by synthresin** [comment]
As soon as I select corrupted Sketch folder in Kactus, same error loop happens, It seems Kactus tries to generate document preview and fails repeatedly 
<img width="937" alt="2018-03-29 11 40 30" src="https://user-images.githubusercontent.com/1055213/38067124-09b5cfb8-3346-11e8-9fd9-545623849187.png">

**Comment by mathieudutour** [comment]
I think it's unrelated. Is there something logged when trying to re-generate the file?

**Comment by synthresin** [comment]
Nothing written in the log. only thing that seems related was console error above.

**Comment by synthresin** [comment]
If you want, I can share private clone of the repo.

**Comment by mathieudutour** [comment]
That'd be perfect yes

**Comment by mathieudutour** [comment]
I fixed your repo, you just have to pull the changes. 

I also fixed the failure in generating the file preview and Kactus is now more resilient when merging.

**Comment by synthresin** [comment]
I'm curious that you think I have to pull, because there was nothing to pull.

**Comment by mathieudutour** [comment]
I push a commit https://github.com/synthresin/tsingtao/commit/daff7c271bee986cc89be76445bf264c621c39d8 so you might have to pull it. Maybe it was pulled automatically.

Anyway, the commit I pushed was just created by updating to 0.3.5 so you can create it back :)
