### ISSUE TITLE
Support for any remote git repo

### ISSUE THREAD

**Issue by tokou** [kactus-io/kactus#95]
## Description

Support for any remote git repo.

## Related 

#88 

## Additional Information

This is more of a feature request. It would be nice to be able to use any git repo as a remote and not just GitHub.

Attached is a screenshot of how SourceTree does it.

![capture d ecran 2018-04-06 a 10 25 13](https://user-images.githubusercontent.com/517070/38410446-e08fce32-3984-11e8-9f54-2fb197f910a6.png)

**Comment by mathieudutour** [comment]
It's already possible. Just clone your repo from any server
