### ISSUE TITLE
Positive Ethereum Phishing Detector by MetaMask.

### ISSUE THREAD

**Issue by Brandon-P** [kactus-io/kactus#96]
## Description
Visited Kactus.io on 04/16/18 and MetaMask blocked it as being positive for ethereum phishing.
see - https://github.com/metamask/eth-phishing-detect
using plugin - MetaMask Chrome Extension v4.5.5

## Version
Website. Wasn't sure were else to report.
* Kactus.io
* Operating system: OS High Sierra

## Steps to Reproduce
1. Install metamask chrome extension.
2. In chrome try and open kactus.io
3. See MetaMask Blocked Page.

### Expected Behavior
Code should not trigger phishing detector.

### Actual Behavior
Some shady code was found.

## Additional Information

![screen shot 2018-04-16 at 2 19 50 pm](https://user-images.githubusercontent.com/3459191/38836164-16162484-4182-11e8-9090-22af27b76deb.png)

**Comment by mathieudutour** [comment]
oO. Do you have any insights about why it has been flagged? There is literally no javascript except google analytics on the website 🤔

**Comment by mathieudutour** [comment]
After investigating, it's because `kactus.io` is fuzzy matching `auctus.org`. I'm sorry but that's a retarded phishing detector...

I'll see if I can add kactus to the whitelist but they just waste people's time...
