### ISSUE TITLE
Unexpected changes after pull

### ISSUE THREAD

**Issue by synthresin** [kactus-io/kactus#97]
## Description

Unexpected JSON changes happens after pull commits from remote. and kactus freezes due to massive changes.

## Version
* Kactus: 0.3.5
* Operating system: macOS 10.13.4

## Steps to Reproduce
It happens every time after I pull new commits and open auto-generated sketch file. 
You can check this issue with video below.

0. quit Kactus
1. hard reset to older commits using terminal
2. open Kactus, delete & regenerate sketch files. (Sketch files is fine at this point)
3. quit and restart kactus.
4. pull latest commits using Kactus
5. open generated sketch file.
6. can find sketch file is corrupted
7. Kactus tries to make changes and throws error.

It works fine when I
1. move to latests commit 
2. delete & regenerate sketch files

### Expected Behavior
There shouldn't be no JSON changes right after pulling.

### Actual Behavior
massive JSON changes happen && file is corrupted

## Additional Information

I uploaded commits to my private repo `tsingtao` which I shared before.
you can reproduce this by rewinding to `ae18baf` and doing these steps above.

You can check unexpected change issue with [this video](https://www.dropbox.com/s/pat8oueosjeby5j/unwantedchanges.mov?dl=0).

Kactus Error
![2018-04-23 1 51 19](https://user-images.githubusercontent.com/1055213/39107470-6e7cdea8-46fd-11e8-904d-dc89eb4ae73d.png)

Massive unexpected changes.
<img width="914" alt="2018-04-23 1 53 49" src="https://user-images.githubusercontent.com/1055213/39107517-c7f0fadc-46fd-11e8-84cc-f925f6941842.png">

### Logs
Console logs
[console.log](https://github.com/kactus-io/kactus/files/1936696/console.log)

Kactus Logs
[2018-04-23.kactus.production.log](https://github.com/kactus-io/kactus/files/1936700/2018-04-23.kactus.production.log)

**Comment by mathieudutour** [comment]
The only reason I can think of is that your Sketch version is not the same as the file you pull so when Kactus receives it, it creates the changes that happen when you update Sketch.

Could that be the case?

**Comment by synthresin** [comment]
If that is the case, I think some changes should be generated after I move to latest commit, delete & regenerate Sketch file (or after opening & saving that Sketch file).but nothing happened, as far as I remember

And I tend to use the latests version as soon as possible.

**Comment by synthresin** [comment]
I've checked that our team uses the same version. but we still get similar issues.

**Comment by synthresin** [comment]
We get same issue again under the same version(50.0)

**Comment by rvr** [comment]
We're seeing a lot of these as well. Seems there are json changes frequently when I haven't made any changes. I've had to clear untracked files and uncommitted changes many times. Sometimes it seems even just opening a generated file creates changes. I'm having a hard time telling what the pattern is, and I can't have confidence that if I commit I won't lose or change work.

It's a lot of changes like this where the diff doesn't seem to be different at all:
<img width="1271" alt="screen shot 2019-01-30 at 9 41 29 pm" src="https://user-images.githubusercontent.com/28814/52027111-34ddd580-24d8-11e9-9680-6c61421ff261.png">

**Comment by mathieudutour** [comment]
What's the JSON diff (if you click on "text" at the bottom, it should show what is the underlying diff)?

**Comment by mathieudutour** [comment]
I think this is fixed in 0.3.19 (which is currently deploying)
